name: Tests & Checks

on:
  workflow_dispatch:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
    paths:
      - src/**/*

jobs:
  test:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [22]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-node-modules-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-node-modules-

      - name: Install Dependencies 📥
        run: bun install --frozen-lockfile

      - name: Check, Lint, Test 🧪
        run: |
          bun run check
          bun run lint
          bun run coverage

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: coverage-report
          path: coverage
          retention-days: 30
